### ISSUE TITLE
GlassHtml.RenderLink does not append media request protection

### ISSUE THREAD

**Issue by rootix** [mikeedwards83/Glass.Mapper#286]
If media request protection is enabled, Sitecore requires the hash on media items, even if it is not an image.   Otherwise the ?la parameter is ignored and Sitecore.Context.Language is used instead.

The GlassHtml.RenderLink and BeginRenderLink method uses the Link.BuildUrl extension to get the url of the target. The method does not apply media request protection to the url if the target is a media item.

I am a bit unsure about the impact this would have on existing solutions if they get around this issue somehow else.

**Comment by mikeedwards83** [comment]
Hi

If you are rendering an image you should be using RenderImage, we append the media hash URL here:

https://github.com/mikeedwards83/Glass.Mapper/blob/master/Source/Glass.Mapper.Sc/GlassHtml.cs#L899

You will need to ensure that your solution references the correct Glass.Mapper.Sc DLL for your version of Sitecore.

Mike

**Comment by rootix** [comment]
Hi Mike

The Link field points to a PDF document in this case. We set the la and vs MediaOptions for all GetMediaUrl calls to prevent Google from indexing wrong stuff. 

Therefore i have to use RenderLink to get the URL of the document. As the hash is missing, the la parameter is ignored by Sitecore and users see possibly wrong documents. As a workaround, i excluded the la and vs parameter from the hash generation which solves the issue for now. 

Since Sitecore applies the media request protection to all media items, not only images, i think it is a must to include the hash to all media links.

**Comment by mikeedwards83** [comment]
Are you using the Glass.Mapper.Sc.Link class? 

Media URLs are generated via the MediaManager, but SC doesn't append the hash at this point. The hash is added during the rendering field pipeline. 

Looking at this pipeline you would have the same issue with the native API.

**Comment by ashugoyal220** [comment]
Hi Mike,

I am facing issue while using @Html.Glass().RenderImage and i am on upgraded version of Glass mapper 4.0.11.63, Still I am getting the same error "MediaRequestProtection: An invalid/missing hash value was encountered. The expected hash value:"

Is it fixed in any specific version?

**Comment by mikeedwards83** [comment]
@ashugoyal220  I don't know if you are still having this issue, please update the issue if you are.

**Comment by amirbantdc** [comment]
Hi Mike,

I am using the 4.1.0.64 glassmapper dll but still facing the the issue "MediaRequestProtection: An invalid/missing hash value was encountered. The expected hash value:". Please check the below image and suggest.

![image](https://user-images.githubusercontent.com/26409395/27834344-e22ff99c-60d6-11e7-9b66-7e5413be7356.png)

Thanks
Anirban

**Comment by cardinal252** [comment]
Is the Sitecore dlls referenced of the right version / does it have the dll's referenced ? - if not, it may default back to the dlls compiled against pre 7.5?

**Comment by mikeedwards83** [comment]
Closing because of the age and no response to the last message from Nat.
